### ISSUE TITLE
exceptions thrown when closing a tab that is actively compiling

### ISSUE THREAD

**Issue by DarkInsanePyro** [maccasoft/spin-tools#3]
### Issue
If a tab is closed while the code is being compiled, once the compilation completes it tries to update disposed UI elements and throws exceptions.

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.custom.CTabItem.setFont(CTabItem.java:399)
	at com.maccasoft.propeller.EditorTab$6$2$1.run(EditorTab.java:584)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	[...]
```

And
```
java.lang.NullPointerException: Cannot invoke "com.maccasoft.propeller.model.Node.getChilds()" because "node" is null
	at com.maccasoft.propeller.OutlineView.setInput(OutlineView.java:426)
	at com.maccasoft.propeller.EditorTab$6$1.run(EditorTab.java:498)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	[...]
```

### Steps to Reproduce
Open several editor tabs, that are related so that when one closes, others will re-compile due to (what I assume) is SourcePool changes. Then invoke the Close All Tabs command from any menu and it should throw these exceptions.

**Comment by maccasoft** [comment]
Actually, I found that there was more going on there, some widgets were not correctly disposed. This should be fixed now.
I tested a bit with multiple dependent editors and seems to work correctly now.

**Comment by DarkInsanePyro** [comment]
Ah, that'd definitely be a better resolution than mine (merely hiding it). I did some testing, and it appears resolved. Thanks.
